# Generated by Django 3.2.4 on 2021-11-24 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_db_logger', '0002_auto_20190109_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
