# Generated by Django 3.2.4 on 2022-08-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(unique=True)),
                ('preprocessing', models.TextField()),
                ('label', models.SmallIntegerField()),
            ],
        ),
    ]
